baseURL = 'https://rosist-sallina.github.io/'
languageCode = 'en'
title = 'Rosist Sallina'
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'en'
[languages]
[languages.en]
languageCode = 'en'
languageName = 'English'
weight = 1
hasCJKLanguage = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
